=== JordanJTY/XmlRESTful/UT3_NoObligatoria/atestadosLasPalmas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.jordancio.com"
    xmlns="https://www.jordancio.com" elementFormDefault="qualified">
    <xs:element name="atestados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="atestado" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DILIG"></xs:element>
                            <xs:element name="LUGAR"></xs:element>
                            <xs:element name="ALTURA_DE"></xs:element>
                            <xs:element name="FECHA"></xs:element>
                            <xs:element name="HORA"></xs:element>
                            <xs:element name="VEHICULOS"></xs:element>
                            <xs:element name="HERIDOS"></xs:element>
                            <xs:element name="DESTINO"></xs:element>
                            <xs:element name="COLISION"></xs:element>
                            <xs:element name="INFR_COND"></xs:element>
                            <xs:element name="INFR_PEAT"></xs:element>
                            <xs:element name="DENUNCIAS"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JordanJTY/XmlRESTful/UT3_NoObligatoria/AtestadosLasPalmas.xml
<?xml version="1.0" encoding="UTF-8"?>
<atestados xmlns="https://www.jordancio.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://www.jordancio.com atestadosLasPalmas.xsd">
    <atestado>
        <DILIG>2</DILIG>
        <LUGAR>SERVENTIA Nº 326</LUGAR>
        <ALTURA_DE />
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>03:20</HORA>
        <VEHICULOS>1</VEHICULOS>
        <HERIDOS>2</HERIDOS>
        <DESTINO>Juzgado</DESTINO>
        <COLISION>Otros</COLISION>
        <INFR_COND>Inexperiencia del conductor</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
    <atestado>
        <DILIG>3</DILIG>
        <LUGAR>AVDA. GUILLERMO SANTANA RIVERO</LUGAR>
        <ALTURA_DE>1</ALTURA_DE>
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>07:50</HORA>
        <VEHICULOS>1</VEHICULOS>
        <HERIDOS>0</HERIDOS>
        <DESTINO>Jefatura</DESTINO>
        <COLISION>Vuelco</COLISION>
        <INFR_COND>Velocidad inadecuada</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
    <atestado>
        <DILIG>7</DILIG>
        <LUGAR>CASABLANCA III</LUGAR>
        <ALTURA_DE>URB. RESIDENCIAL MESTISAY</ALTURA_DE>
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>14:15</HORA>
        <VEHICULOS>2</VEHICULOS>
        <HERIDOS>0</HERIDOS>
        <DESTINO>Jefatura</DESTINO>
        <COLISION>Colisión</COLISION>
        <INFR_COND>Sin definir</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
</atestados>

=== JordanJTY/XmlRESTful/UT3_NoObligatoria/atestadoLasPalmas2.xml
<?xml version="1.0" encoding="UTF-8"?>

<atestados xmlns="https://www.jordancio.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://www.jordancio.com atestadosLasPalmas.xsd">
    <atestado>
        <DILIG>5</DILIG>
        <LUGAR>PUENTE ELEVADO LA BALLENA</LUGAR>
        <ALTURA_DE />
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>06:20</HORA>
        <VEHICULOS>2</VEHICULOS>
        <HERIDOS>1</HERIDOS>
        <DESTINO>Jefatura</DESTINO>
        <COLISION>Colisión</COLISION>
        <INFR_COND>No mantener el intervalo seg.</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
    <atestado>
        <DILIG>6</DILIG>
        <LUGAR>ANA BENITEZ</LUGAR>
        <ALTURA_DE>1</ALTURA_DE>
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>14:00</HORA>
        <VEHICULOS>6</VEHICULOS>
        <HERIDOS>0</HERIDOS>
        <DESTINO>Jefatura</DESTINO>
        <COLISION>Colisión</COLISION>
        <INFR_COND>Sin definir</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
    <atestado>
        <DILIG>8</DILIG>
        <LUGAR>ROTONDA EL CARDON</LUGAR>
        <ALTURA_DE>ARCHIVERO JOAQUIN BLANCO MONTESDEOCA</ALTURA_DE>
        <FECHA>2014-01-01T00:00:00</FECHA>
        <HORA>09:45</HORA>
        <VEHICULOS>2</VEHICULOS>
        <HERIDOS>0</HERIDOS>
        <DESTINO>Juzgado</DESTINO>
        <COLISION>Colisión</COLISION>
        <INFR_COND>No mantener el intervalo seg.</INFR_COND>
        <INFR_PEAT>Ninguna infracción</INFR_PEAT>
        <DENUNCIAS>0</DENUNCIAS>
    </atestado>
</atestados>
